config/routes.rb
Rails.application.routes.draw do
  get 'signups/new'

  get 'sessions/new'

  get 'welcome/index'

  get 'signups' => 'signups#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  root 'welcome#index'

  resources :submissions do
    resources :reviews
  end

  resources :signups

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :submission

  VERDICT = %w(Pass Pursue)

  validates :user_id, presence: true
  validates_inclusion_of :verdict, :in => VERDICT


  def getReviewer
    if user_id != nil
      @reviewer = User.find(user_id)
    end
  end

  def getReviewerEmail
    if user_id != nil
      @reviewer_email = User.find(user_id).email
    else
      @reviewer_email = 'unknown'
    end
  end
end

app/models/signup.rb
class Signup < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  has_secure_password

  validates :password, presence: true, length: {minimum: 6}
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  has_many :reviews

  validates :user_id, presence: true
  validate :has_submission

  def has_submission
    if !self.link.present? && !self.file_data.present?
      self.errors[:base] << 'Need at least a submission link or file.'
    end
  end

  def getCandidate
    if user_id.nil?
      @candidate = nil
    else
      @candidate = User.find(user_id)
    end
  end

  def getCandidateEmail
    if user_id.nil?
      @candidate_email = 'unknown'
    else
      @candidate = User.find(user_id).email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticated_or_redirect_to_login

  def index
    @submission = Submission.find(params[:submission_id])
    @reviews = @submission.reviews
  end

  def new

  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to submission_review_path(@review.submission, @review)
    else
      render :action => 'edit'
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  # TODO ideally this method only works for logged in user.
  # Reviewer ID is current logged in user ; TODO check user permissions to review
  def create
    if current_user.nil?
      redirect_to login_path
    else
      @submission = Submission.find(params[:submission_id])
      @review = @submission.reviews.create(review_params) do |r|
        r.user_id = current_user.id
      end
      if @review.save
        redirect_to(submission_review_path(@review.submission, @review))
      else
        render :action => 'new'
      end
    end
  end

  private
  def review_params
    params.require(:review).permit(:feedback, :verdict)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = Signup.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to submissions_path
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:notice] = 'You have successfully logged out.'
    redirect_to root_url
  end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

  before_action :authenticated_or_redirect_to_login, :except => [:new, :create]

  def show
    @signup = Signup.find(params[:id])
  end

  def new
    @signup = Signup.new
  end

  def index

  end

  def create
    @signup = Signup.new(user_params)
    if @signup.save
      log_in @signup
      flash[:notice] = "Welcome to the Online Submission!"
      redirect_to @signup
    else
      render 'new'
      flash.now[:danger] = 'New User is not created'
    end
  end

  private
  def user_params
    params.require(:signup).permit(:name, :email, :password,
                                   :password_confirmation)
  end
end

app/controllers/submissions_controller.rb
require 'net/http'

class SubmissionsController < ApplicationController

  include FileHelper

  before_action :authenticated_or_redirect_to_login

  def index
    @submissions = Submission.all
  end

  def new
    @submission = Submission.new
  end

  def show
    @submission = Submission.find(params[:id])
  end

  # Only download in the submissions/ folder for now.
  # TODO re-implement to download over HTTP
  def download(submission)
    if (submission.filename != nil)
      user_id = submission.user_id ||= 'user_id_0'
      dir = 'submissions/' + user_id + '/'
      create_dir_struc(dir)
      File.new(dir + submission.filename, 'wb') { |file|
        file.write(submission.file_data)
      }
    end
  end

  # TODO If submission user id is already given and submission user id != current user id:
  #    This is the scenario when an admin adds a submission for a candidate.
  #    Need to check current user permissions to perform that action!
  def create
    @submission = Submission.new(submission_params) do |t|
      t.user_id = params[:user_id] || current_user.id
      if (params[:submission][:file])
        t.filename = ActionController::Base.helpers.sanitize(params[:submission][:file].original_filename)
        t.file_content_type = params[:submission][:file].content_type
        t.file_data = params[:submission][:file].read
      end
      if (params[:submission][:link])
        t.link = params[:submission][:link]
      end
    end
    if @submission.save
      flash[:notice] = 'Submission successfully saved \./'
      redirect_to (@submission)
    else
      flash[:alert] = 'This submission could not be saved /.\\'
      render :action => 'new'
    end
  end

  private
  def submission_params
    params.require(:submission).permit(:link)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def hello
    render text: "hello world!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_helper.rb
require 'fileutils'

module FileHelper

  def create_dir_struc(path)
    dirname = File.dirname(path)
    unless File.directory?(dirname)
      FileUtils.mkdir_p(dirname)
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(signup)
    session[:signup_id] = signup.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= Signup.find_by(id: session[:signup_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:signup_id)
    @current_user = nil
  end

  def authenticated_or_redirect_to_login
    unless logged_in?
      flash.alert = 'You must login to perform that action'
      redirect_to login_path
    end
  end

end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Pass or Pursue", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
            <!-- <li><%= link_to "Users", '#' %></li> -->
            <li><%= link_to "Submissions", submissions_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passpursue</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: 'alert alert-info' %>
  <% end %>
  <%= yield %>
  <!-- <%= debug(params) if Rails.env.development? %> -->
</div>
</body>
</html>

app/views/reviews/edit.html.erb
<h1>Edit review <%= @review.id %></h1>

<%= form_for :review, url: submission_review_path(@review.submission, @review), method: :patch do |f| %>
    <p>
      <%= f.label :verdict %>
      <%= f.collection_select :verdict, Review::VERDICT, :to_s, :to_s %> <br>
      <%= f.label :feedback %>
      <%= f.text_area :feedback %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Cancel and go back to review', submission_review_path(@review.submission, @review) %>

app/views/reviews/index.html.erb
<p>All reviews for submission <%= link_to @submission.id, submission_path(@submission) %> </p>

<table>
  <tr>
    <th>Reviewer</th>
    <th>Verdict</th>
    <th>Feedback</th>
    <th colspan="1"></th>
  </tr>

  <% @submission.reviews.each do |review| %>
      <tr>
        <td><%= review.getReviewerEmail %></td>
        <td><%= review.verdict %></td>
        <td><%= review.feedback %></td>
        <td><%= link_to 'Edit review', edit_submission_review_path(review.submission, review) %></td>
      </tr>
  <% end %>
</table>

app/views/reviews/new.html.erb
<p>Please enter your feedback and verdict here. Thanks :)</p>

<%= form_for :review, url: submission_reviews_path do |f| %>
    <p>
      <%= f.label :verdict %>
      <%= f.collection_select :verdict, Review::VERDICT, :to_s, :to_s %> <br>
      <%= f.label :feedback %>
      <%= f.text_area :feedback %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/reviews/show.html.erb
<h1>Review of submission <%= @review.submission.id %></h1>

<p>
  <strong>Reviewer:</strong> <%= @review.getReviewerEmail %>
</p>

<p>
  <strong>Verdict:</strong> <%= @review.verdict %>
</p>

<p>
  <strong>Feedback:</strong> <%= @review.feedback %>
</p>

<p>
  <%= link_to 'See submission ' + @review.submission.id.to_s, submission_path(@review.submission) %>
</p>

<p>
  <%= link_to 'Back to submissions', submissions_path %>
</p>

app/views/signups/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@signup, url: signups_path) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
        
        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/signups/show.html.erb
<% provide(:title, @signup.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @signup.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/submissions/index.html.erb
<p> <%= link_to 'Add a submission', new_submission_path %></p>

<h1>All code submissions <%= image_tag('allthethings.png', alt: '(allthethings)') %></h1>

<table>
  <tr>
    <th>Submission ID</th>
    <th>Candidate Email</th>
    <th>Link to submission</th>
    <th>Submission file</th>
    <th>Submission Reviews</th>
    <th></th>
  </tr>

  <% @submissions.each do |submission| %>
      <tr>
        <td> <%= link_to '#' + submission.id.to_s, submission_path(submission) %></td>
        <td><%= submission.getCandidateEmail %></td>
        <td>
          <% if submission.link.present? %>
              <%= link_to submission.link, url_with_protocol(submission.link) %></td>
          <% else %>
              -
          <% end %>
          <td>
            <% if submission.filename.present? %>
                <%= submission.filename %></td>
            <% else %>
                -
            <% end %>
            <td>
              <% if submission.reviews.present? %>
                  <% submission.reviews.first(2).each do |review| %>
                      <p>
                        <strong>Reviewer:</strong> <%= review.getReviewerEmail %>
                        <strong>Verdict:</strong> <%= review.verdict %>
                        <%= link_to 'Full review', {controller: 'reviews', action: 'show', submission_id: submission.id, id: review.id} %>
                      </p>
                  <% end %>
                  <p><%= link_to 'See all reviews', submission_reviews_path(submission) %></p>
              <% else %>
                  No review yet :(
              <% end %>
            </td>
            <td><%= link_to 'Write a review', {controller: 'reviews', action: 'new', submission_id: submission.id} %></td>
            </tr>
  <% end %>
</table>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<h2>You can upload and/or provide a link to your submission.</h2>

<%= form_for :submission, url: submissions_path do |f| %>

    <% if @submission.errors.any? %>
        <div id='error_msg'>
          <h2>
            <%= pluralize(@submission.errors.count, 'error') %> prohibited
            this submission from being saved:
          </h2>
          <ul>
            <% @submission.errors.full_messages.each do |msg| %>
                <li>
                  <%= "#{msg}" %>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.file_field :file %>
    </p>

    <p>
      <%= f.label :link %>
      <%= f.text_area :link %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<p>
  <%= link_to 'Go back to all submissions', submissions_path %>
</p>

app/views/submissions/show.html.erb
<p>
  <strong>Candidate:</strong>
  <%= @submission.user_id %>
</p>

<p>
  <strong>Submission title:</strong>
  <%= @submission.filename %>
</p>

<p>
  <strong>Submission link:</strong>
  <%= link_to @submission.link, url_with_protocol(@submission.link) %></a>
</p>

<p>
  <%= link_to 'See Reviews', submission_reviews_path(@submission) %>
</p>

<p>
  <%= link_to 'Go back to all submissions', submissions_path %>
</p>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>Pass or Pursue</h1>

  <%= link_to 'Candidates submissions', controller: 'submissions' %>

  <h5>
    Ideally this page should become the login page username/password, with an option to sign up. <br>
    Users with an email matching *@covata.com would be granted permission to view and review submissions and other's
    comments <br>
    Users with any other email would be able to sign up, login, and post a submission.<br>
  </h5>

  <%= link_to "Sign up now!", signups_path, class: "btn btn-lg btn-primary" %>

</div>